spring:
    application:
        name: todos-gateway
logging:
    level:
        io.corbs: DEBUG
server:
    port: 9999
management:
    endpoints:
        web:
            base-path: /ops
            exposure:
                include: '*'
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
todos:
    api:
        endpoint: http://localhost:8080/todos
    ui:
        endpoint: http://localhost:4040
#todos-api:
#    ribbon:
#        listOfServers: localhost:8080
# Router configuration
zuul:
    routes:
        ops:
            path: /ops/**
            url: forward:/ops        
        api:
            path: /api/**
            stripPrefix: true
#            url: ${todos.api.endpoint}
        ui:
            path: /**
            url: ${todos.ui.endpoint}
