server:
    port: 9999
spring:
    application:
        name: todos-gateway
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka        
management:
    endpoints:
        web:
            base-path: /ops
            exposure:
                include: '*'
todos:
    api:
        endpoint: http://localhost:8080/todos
    web:
        endpoint: http://localhost:4040
# Router configuration
zuul:
    routes:
        todos-gateway-ops:
            path: /ops/**
            url: forward:/ops        
        todos-api:
            path: /api/**
            url: ${todos.api.endpoint}            
        todos-web:
            path: /**
            url: ${todos.web.endpoint}
