spring:
    application:
        name: todos-gateway
logging:
    level:
        io.corbs: DEBUG
server:
    port: 9999
management:
    endpoints:
        web:
            base-path: /ops
            exposure:
                include: '*'
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
# Router configuration
zuul:
    routes:
        ops:
            path: /ops/**
            url: forward:/ops        
        api:
            path: /api/**
            url: http://localhost:8080
        ui:
            path: /**
            url: http://localhost:4040
# We let zuul handle routing to the Target url for /api/**
# by configuring zuul.routes, however
# We can active which /api/** to plugin by starting up with:
# --todos-api-mode=simple OR --todos-api-mode=cqrs
#todos:
#  api:
#    mode: cqrs